server:
  port: 8088
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bug_agent?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6380
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 220MB
  sql:
    init:
      mode: always

app:
  workspace-root: ./workspace
